# Generated by Django 3.2 on 2021-05-03 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('creation_date', models.DateTimeField(verbose_name='created')),
                ('validity_flag', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(verbose_name='modified')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('creation_date', models.DateTimeField(verbose_name='created')),
                ('validity_flag', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(verbose_name='modified')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.directory')),
            ],
        ),
        migrations.CreateModel(
            name='SectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Procedure section'), (2, 'Property section'), (3, 'Lemma section'), (4, 'Assertion section'), (5, 'Precondition section'), (6, 'Postcondition section')])),
                ('validity_flag', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(verbose_name='modified')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Proved'), (2, 'Invalid'), (3, 'Counterexample'), (4, 'Unchecked')])),
                ('validity_flag', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(verbose_name='modified')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('validity_flag', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(verbose_name='modified')),
            ],
        ),
        migrations.CreateModel(
            name='StatusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_data', models.CharField(max_length=1000)),
                ('validity_flag', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(verbose_name='modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.user')),
            ],
        ),
        migrations.CreateModel(
            name='FileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('creation_date', models.DateTimeField(verbose_name='created')),
                ('validity_flag', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(verbose_name='modified')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='media.sectioncategory')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.file')),
                ('parent_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.filesection')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='media.status')),
                ('status_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='media.statusdata')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.user'),
        ),
        migrations.AddField(
            model_name='directory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.user'),
        ),
        migrations.AddField(
            model_name='directory',
            name='parent_directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.directory'),
        ),
    ]
