# Generated by Django 3.2 on 2021-05-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='source',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
