# Generated by Django 3.2 on 2021-05-10 18:49

from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_file_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesection',
            name='line',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='source',
            field=models.FileField(null=True, upload_to=media.models.get_filename),
        ),
        migrations.AlterField(
            model_name='sectioncategory',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Invariant section'), (2, 'Variant section'), (3, 'Assertion section'), (4, 'Precondition section'), (5, 'Postcondition section')]),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Proved'), (2, 'Invalid'), (3, 'Counterexample'), (4, 'Error'), (5, 'Unchecked')]),
        ),
        migrations.AlterField(
            model_name='statusdata',
            name='status_data',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
