# Generated by Django 3.2 on 2021-05-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20210512_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
